/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : string, 'quantity' : bigint }
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'total' : bigint,
  'buyer' : Principal,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null };
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'seller' : Principal,
  'category' : string,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export interface ProductInput {
  'name' : string,
  'description' : string,
  'category' : string,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export interface Review {
  'productId' : string,
  'comment' : string,
  'buyerId' : Principal,
  'timestamp' : bigint,
  'rating' : number,
  'buyerName' : string,
  'reviewId' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[ProductInput], string>,
  'addReview' : ActorMethod<[string, number, string], undefined>,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<[], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBuyerOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getProductAverageRating' : ActorMethod<[string], number>,
  'getProductReviews' : ActorMethod<[string], Array<Review>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getSellerOrders' : ActorMethod<[], Array<Order>>,
  'getSellerProducts' : ActorMethod<[Principal], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateCartItem' : ActorMethod<[string, bigint], undefined>,
  'updateProduct' : ActorMethod<[string, ProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];